name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout shared crates
      uses: actions/checkout@v4
      with:
          repository: warthog33/kdfs
          path: kdfs
          
    - name: Checkout main repo
      uses: actions/checkout@v4
   
    - name: Build
      run: cargo build --verbose
      env: 
        CARGO_PATH_CRATES_IO_MY_CRATE: "{ path = 'kdfs' }"
      
    - name: Run tests
      run: cargo test --verbose
      env: 
        CARGO_PATH_CRATES_IO_MY_CRATE: "{ path = 'kdfs' }"
